#!/bin/bash

# Download scripts and move them to /bin
cd
git clone https://github.com/slashtechno/announce-it.git
cd announce-it
sudo cp announce-it /bin
sudo cp post-announcement /bin
sudo chmod +x /bin/post-announcement
sudo chmod +x /bin/announce-it
cd ..
sudo rm -r announce-it
# Install dependencies
sudo apt install nodejs npm -y
npm install serve -g
sudo apt-get install systemd -y
sudo mkdir /etc/announce_board/
sudo chmod 777 /etc/announce_board/
