#!/bin/bash

# Download scripts and move them to /bin


# Install dependencies
sudo apt install nodejs npm -y
npm install serve -g
sudo apt-get install systemd -y
mkdir /etc/announce_board/
chmod 777 /etc/announce_board/
