#!/bin/bash

# Download scripts and move them to /bin
cd
git clone https://github.com/slashtechno/announce-it.git
cd announce-it
sudo cp announce-it /bin
#sudo cp post-announcement /bin
sudo cp serveit /bin
#sudo chmod +x /bin/post-announcement
sudo chmod +x /bin/announce-it
sudo chmod +x /bin/serveit
sudo cp announce-it.service /etc/systemd/system/announce-it.service
sudo systemctl daemon-reload
sudo systemctl enable announce-it.service
sudo systemctl start announce-it.service
# Install dependencies
sudo apt install nodejs npm -y
sudo npm install serve -g
sudo apt-get install systemd -y
sudo mkdir /etc/announce_board/
sudo chmod 777 /etc/announce_board/
cd ..
sudo rm -r announce-it
